pipeline {
    agent any

    environment {
        DOCKER_CREDS = credentials('dockerhub-creds')
        IMAGE_BACKEND = "${DOCKER_CREDS_USR}/backend-app"
        IMAGE_FRONTEND = "${DOCKER_CREDS_USR}/frontend-app"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/tulasids5/taomish-devops-assignment.git'
            }
        }

        stage('Build Backend') {
            steps {
                sh 'mvn -f app/backend/pom.xml clean package -DskipTests'
            }
        }

        stage('Build Frontend') {
            steps {
                dir('app/frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh """
                docker build -t ${IMAGE_BACKEND}:v1 -f docker/Dockerfile.backend app/backend
                docker build -t ${IMAGE_FRONTEND}:v1 -f docker/Dockerfile.frontend app/frontend
                """
            }
        }

        stage('Docker Login & Push') {
            steps {
                sh """
                echo ${DOCKER_CREDS_PSW} | docker login -u ${DOCKER_CREDS_USR} --password-stdin
                docker push ${IMAGE_BACKEND}:v1
                docker push ${IMAGE_FRONTEND}:v1
                """
            }
        }
    }

    post {
        success {
            echo "SUCCESS: Backend + Frontend CI/CD Completed "
        }
        failure {
            echo "FAILED "
        }
    }
}
